export const rows = [
  {
    name: 'Ethan',
    gender: 'Female',
    company: 'Apple',
    age: 49,
    email: 'ethan0@apple.com',
    country: 'France',
    jobTitle: 'Consultant',
    department: 'Finance',
  },
  {
    name: 'Ethan',
    gender: 'Male',
    company: 'Meta',
    age: 25,
    email: 'ethan1@meta.com',
    country: 'Germany',
    jobTitle: 'Designer',
    department: 'Operations',
  },
  {
    name: 'Sophia',
    gender: 'Male',
    company: 'Amazon',
    age: 37,
    email: 'sophia2@amazon.com',
    country: 'France',
    jobTitle: 'Analyst',
    department: 'Operations',
  },
  {
    name: 'Isabella',
    gender: 'Female',
    company: 'KFC',
    age: 24,
    email: 'isabella3@kfc.com',
    country: 'UK',
    jobTitle: 'Engineer',
    department: 'HR',
  },
  {
    name: 'Noah',
    gender: 'Male',
    company: 'Meta',
    age: 60,
    email: 'noah4@meta.com',
    country: 'UK',
    jobTitle: 'Designer',
    department: 'HR',
  },
  {
    name: 'Amelia',
    gender: 'Female',
    company: 'Amazon',
    age: 43,
    email: 'amelia5@amazon.com',
    country: 'India',
    jobTitle: 'Designer',
    department: 'Marketing',
  },
  {
    name: 'Logan',
    gender: 'Female',
    company: 'Apple',
    age: 33,
    email: 'logan6@apple.com',
    country: 'Australia',
    jobTitle: 'Manager',
    department: 'Support',
  },
  {
    name: 'Olivia',
    gender: 'Male',
    company: 'Microsoft',
    age: 60,
    email: 'olivia7@microsoft.com',
    country: 'France',
    jobTitle: 'Consultant',
    department: 'HR',
  },
  {
    name: 'Evelyn',
    gender: 'Female',
    company: 'Microsoft',
    age: 32,
    email: 'evelyn8@microsoft.com',
    country: 'Brazil',
    jobTitle: 'Designer',
    department: 'Support',
  },
  {
    name: 'Aiden',
    gender: 'Male',
    company: 'KFC',
    age: 60,
    email: 'aiden9@kfc.com',
    country: 'Kenya',
    jobTitle: 'Manager',
    department: 'Finance',
  },
  {
    name: 'Evelyn',
    gender: 'Male',
    company: 'Meta',
    age: 28,
    email: 'evelyn10@meta.com',
    country: 'Germany',
    jobTitle: 'Specialist',
    department: 'IT',
  },
  {
    name: 'Dany',
    gender: 'Male',
    company: 'Amazon',
    age: 59,
    email: 'dany11@amazon.com',
    country: 'UK',
    jobTitle: 'Designer',
    department: 'HR',
  },
  {
    name: 'Noah',
    gender: 'Female',
    company: 'Netflix',
    age: 36,
    email: 'noah12@netflix.com',
    country: 'Kenya',
    jobTitle: 'Manager',
    department: 'IT',
  },
  {
    name: 'Sophia',
    gender: 'Male',
    company: 'Swimlane',
    age: 27,
    email: 'sophia13@swimlane.com',
    country: 'USA',
    jobTitle: 'Manager',
    department: 'HR',
  },
  {
    name: 'James',
    gender: 'Female',
    company: 'Netflix',
    age: 56,
    email: 'james14@netflix.com',
    country: 'Brazil',
    jobTitle: 'Engineer',
    department: 'Support',
  },
  {
    name: 'Noah',
    gender: 'Male',
    company: 'Apple',
    age: 29,
    email: 'noah15@apple.com',
    country: 'Germany',
    jobTitle: 'Manager',
    department: 'Finance',
  },
  {
    name: 'Charlotte',
    gender: 'Female',
    company: 'Swimlane',
    age: 60,
    email: 'charlotte16@swimlane.com',
    country: 'Kenya',
    jobTitle: 'Analyst',
    department: 'Operations',
  },
  {
    name: 'Sophia',
    gender: 'Male',
    company: 'Amazon',
    age: 28,
    email: 'sophia17@amazon.com',
    country: 'France',
    jobTitle: 'Consultant',
    department: 'Finance',
  },
  {
    name: 'Aiden',
    gender: 'Female',
    company: 'Netflix',
    age: 41,
    email: 'aiden18@netflix.com',
    country: 'USA',
    jobTitle: 'Specialist',
    department: 'HR',
  },
  {
    name: 'Isabella',
    gender: 'Female',
    company: 'KFC',
    age: 42,
    email: 'isabella19@kfc.com',
    country: 'Brazil',
    jobTitle: 'Developer',
    department: 'Marketing',
  },
  {
    name: 'Noah',
    gender: 'Male',
    company: 'Tesla',
    age: 52,
    email: 'noah20@tesla.com',
    country: 'India',
    jobTitle: 'Analyst',
    department: 'Sales',
  },
  {
    name: 'James',
    gender: 'Female',
    company: 'Amazon',
    age: 34,
    email: 'james21@amazon.com',
    country: 'India',
    jobTitle: 'Consultant',
    department: 'Operations',
  },
  {
    name: 'Noah',
    gender: 'Male',
    company: 'Amazon',
    age: 47,
    email: 'noah22@amazon.com',
    country: 'Australia',
    jobTitle: 'Specialist',
    department: 'Support',
  },
  {
    name: 'Aiden',
    gender: 'Male',
    company: 'Microsoft',
    age: 36,
    email: 'aiden23@microsoft.com',
    country: 'Kenya',
    jobTitle: 'Specialist',
    department: 'Operations',
  },
  {
    name: 'Molly',
    gender: 'Male',
    company: 'Meta',
    age: 27,
    email: 'molly24@meta.com',
    country: 'USA',
    jobTitle: 'Specialist',
    department: 'HR',
  },
  {
    name: 'Charlotte',
    gender: 'Female',
    company: 'Swimlane',
    age: 41,
    email: 'charlotte25@swimlane.com',
    country: 'Brazil',
    jobTitle: 'Specialist',
    department: 'Marketing',
  },
  {
    name: 'Olivia',
    gender: 'Female',
    company: 'Netflix',
    age: 40,
    email: 'olivia26@netflix.com',
    country: 'Canada',
    jobTitle: 'Developer',
    department: 'Sales',
  },
  {
    name: 'Lucas',
    gender: 'Male',
    company: 'Microsoft',
    age: 58,
    email: 'lucas27@microsoft.com',
    country: 'France',
    jobTitle: 'Architect',
    department: 'Sales',
  },
  {
    name: 'Olivia',
    gender: 'Male',
    company: 'Swimlane',
    age: 35,
    email: 'olivia28@swimlane.com',
    country: 'UK',
    jobTitle: 'Manager',
    department: 'Sales',
  },
  {
    name: 'Isabella',
    gender: 'Female',
    company: 'Swimlane',
    age: 54,
    email: 'isabella29@swimlane.com',
    country: 'France',
    jobTitle: 'Analyst',
    department: 'Finance',
  },
  {
    name: 'Austin',
    gender: 'Male',
    company: 'Burger King',
    age: 30,
    email: 'austin30@burgerking.com',
    country: 'UK',
    jobTitle: 'Specialist',
    department: 'Finance',
  },
  {
    name: 'Aiden',
    gender: 'Male',
    company: 'Microsoft',
    age: 41,
    email: 'aiden31@microsoft.com',
    country: 'France',
    jobTitle: 'Engineer',
    department: 'Sales',
  },
  {
    name: 'Emma',
    gender: 'Female',
    company: 'KFC',
    age: 24,
    email: 'emma32@kfc.com',
    country: 'Japan',
    jobTitle: 'Architect',
    department: 'Sales',
  },
  {
    name: 'Olivia',
    gender: 'Male',
    company: 'Tesla',
    age: 38,
    email: 'olivia33@tesla.com',
    country: 'Canada',
    jobTitle: 'Engineer',
    department: 'Marketing',
  },
  {
    name: 'Logan',
    gender: 'Female',
    company: 'Swimlane',
    age: 32,
    email: 'logan34@swimlane.com',
    country: 'India',
    jobTitle: 'Analyst',
    department: 'Finance',
  },
  {
    name: 'Austin',
    gender: 'Female',
    company: 'Burger King',
    age: 41,
    email: 'austin35@burgerking.com',
    country: 'Kenya',
    jobTitle: 'Consultant',
    department: 'Marketing',
  },
  {
    name: 'Harper',
    gender: 'Male',
    company: 'Meta',
    age: 32,
    email: 'harper36@meta.com',
    country: 'Australia',
    jobTitle: 'Engineer',
    department: 'HR',
  },
  {
    name: 'Emma',
    gender: 'Male',
    company: 'Amazon',
    age: 56,
    email: 'emma37@amazon.com',
    country: 'Canada',
    jobTitle: 'Developer',
    department: 'Legal',
  },
  {
    name: 'Noah',
    gender: 'Female',
    company: 'Burger King',
    age: 49,
    email: 'noah38@burgerking.com',
    country: 'Australia',
    jobTitle: 'Developer',
    department: 'IT',
  },
  {
    name: 'Noah',
    gender: 'Male',
    company: 'Swimlane',
    age: 59,
    email: 'noah39@swimlane.com',
    country: 'India',
    jobTitle: 'Analyst',
    department: 'Sales',
  },
  {
    name: 'James',
    gender: 'Male',
    company: 'Meta',
    age: 56,
    email: 'james40@meta.com',
    country: 'Germany',
    jobTitle: 'Architect',
    department: 'Marketing',
  },
  {
    name: 'Evelyn',
    gender: 'Female',
    company: 'Amazon',
    age: 32,
    email: 'evelyn41@amazon.com',
    country: 'India',
    jobTitle: 'Specialist',
    department: 'Legal',
  },
  {
    name: 'Mia',
    gender: 'Female',
    company: 'Microsoft',
    age: 45,
    email: 'mia42@microsoft.com',
    country: 'UK',
    jobTitle: 'Developer',
    department: 'Support',
  },
  {
    name: 'Mason',
    gender: 'Female',
    company: 'KFC',
    age: 27,
    email: 'mason43@kfc.com',
    country: 'Germany',
    jobTitle: 'Consultant',
    department: 'Sales',
  },
  {
    name: 'Mia',
    gender: 'Male',
    company: 'Google',
    age: 40,
    email: 'mia44@google.com',
    country: 'France',
    jobTitle: 'Specialist',
    department: 'Support',
  },
  {
    name: 'Ethan',
    gender: 'Male',
    company: 'Google',
    age: 22,
    email: 'ethan45@google.com',
    country: 'Kenya',
    jobTitle: 'Architect',
    department: 'HR',
  },
  {
    name: 'Liam',
    gender: 'Female',
    company: 'Burger King',
    age: 24,
    email: 'liam46@burgerking.com',
    country: 'Brazil',
    jobTitle: 'Architect',
    department: 'HR',
  },
  {
    name: 'Austin',
    gender: 'Female',
    company: 'KFC',
    age: 48,
    email: 'austin47@kfc.com',
    country: 'India',
    jobTitle: 'Developer',
    department: 'Marketing',
  },
  {
    name: 'Aiden',
    gender: 'Male',
    company: 'Swimlane',
    age: 23,
    email: 'aiden48@swimlane.com',
    country: 'Japan',
    jobTitle: 'Analyst',
    department: 'Marketing',
  },
  {
    name: 'James',
    gender: 'Female',
    company: 'KFC',
    age: 52,
    email: 'james49@kfc.com',
    country: 'Kenya',
    jobTitle: 'Specialist',
    department: 'Operations',
  },
  {
    name: 'Dany',
    gender: 'Male',
    company: 'Netflix',
    age: 56,
    email: 'dany50@netflix.com',
    country: 'Brazil',
    jobTitle: 'Designer',
    department: 'IT',
  },
  {
    name: 'Emma',
    gender: 'Male',
    company: 'Tesla',
    age: 35,
    email: 'emma51@tesla.com',
    country: 'USA',
    jobTitle: 'Architect',
    department: 'Operations',
  },
  {
    name: 'Ethan',
    gender: 'Male',
    company: 'Apple',
    age: 48,
    email: 'ethan52@apple.com',
    country: 'Germany',
    jobTitle: 'Manager',
    department: 'HR',
  },
  {
    name: 'Mason',
    gender: 'Male',
    company: 'Meta',
    age: 33,
    email: 'mason53@meta.com',
    country: 'USA',
    jobTitle: 'Engineer',
    department: 'Marketing',
  },
  {
    name: 'Harper',
    gender: 'Female',
    company: 'Apple',
    age: 53,
    email: 'harper54@apple.com',
    country: 'USA',
    jobTitle: 'Architect',
    department: 'HR',
  },
  {
    name: 'Aiden',
    gender: 'Male',
    company: 'KFC',
    age: 52,
    email: 'aiden55@kfc.com',
    country: 'Kenya',
    jobTitle: 'Designer',
    department: 'Support',
  },
  {
    name: 'Olivia',
    gender: 'Female',
    company: 'Burger King',
    age: 57,
    email: 'olivia56@burgerking.com',
    country: 'Kenya',
    jobTitle: 'Engineer',
    department: 'Operations',
  },
  {
    name: 'Dany',
    gender: 'Male',
    company: 'Burger King',
    age: 59,
    email: 'dany57@burgerking.com',
    country: 'India',
    jobTitle: 'Consultant',
    department: 'HR',
  },
  {
    name: 'Austin',
    gender: 'Male',
    company: 'Tesla',
    age: 38,
    email: 'austin58@tesla.com',
    country: 'Kenya',
    jobTitle: 'Engineer',
    department: 'Legal',
  },
  {
    name: 'Noah',
    gender: 'Male',
    company: 'Netflix',
    age: 55,
    email: 'noah59@netflix.com',
    country: 'Japan',
    jobTitle: 'Designer',
    department: 'Marketing',
  },
  {
    name: 'Mia',
    gender: 'Female',
    company: 'Microsoft',
    age: 45,
    email: 'mia60@microsoft.com',
    country: 'Canada',
    jobTitle: 'Designer',
    department: 'Legal',
  },
  {
    name: 'Mia',
    gender: 'Male',
    company: 'Microsoft',
    age: 46,
    email: 'mia61@microsoft.com',
    country: 'Australia',
    jobTitle: 'Specialist',
    department: 'Legal',
  },
  {
    name: 'Ethan',
    gender: 'Male',
    company: 'Apple',
    age: 37,
    email: 'ethan62@apple.com',
    country: 'France',
    jobTitle: 'Manager',
    department: 'IT',
  },
  {
    name: 'Mason',
    gender: 'Female',
    company: 'Google',
    age: 27,
    email: 'mason63@google.com',
    country: 'France',
    jobTitle: 'Analyst',
    department: 'Support',
  },
  {
    name: 'Charlotte',
    gender: 'Male',
    company: 'Meta',
    age: 54,
    email: 'charlotte64@meta.com',
    country: 'Germany',
    jobTitle: 'Consultant',
    department: 'IT',
  },
  {
    name: 'James',
    gender: 'Male',
    company: 'Meta',
    age: 36,
    email: 'james65@meta.com',
    country: 'Australia',
    jobTitle: 'Specialist',
    department: 'Sales',
  },
  {
    name: 'Evelyn',
    gender: 'Female',
    company: 'Amazon',
    age: 27,
    email: 'evelyn66@amazon.com',
    country: 'Australia',
    jobTitle: 'Designer',
    department: 'HR',
  },
  {
    name: 'Isabella',
    gender: 'Female',
    company: 'Apple',
    age: 50,
    email: 'isabella67@apple.com',
    country: 'Kenya',
    jobTitle: 'Manager',
    department: 'Finance',
  },
  {
    name: 'Charlotte',
    gender: 'Male',
    company: 'Meta',
    age: 48,
    email: 'charlotte68@meta.com',
    country: 'Brazil',
    jobTitle: 'Architect',
    department: 'Legal',
  },
  {
    name: 'Isabella',
    gender: 'Male',
    company: 'Apple',
    age: 31,
    email: 'isabella69@apple.com',
    country: 'UK',
    jobTitle: 'Manager',
    department: 'HR',
  },
  {
    name: 'Aiden',
    gender: 'Male',
    company: 'Google',
    age: 24,
    email: 'aiden70@google.com',
    country: 'India',
    jobTitle: 'Analyst',
    department: 'Legal',
  },
  {
    name: 'Evelyn',
    gender: 'Female',
    company: 'Burger King',
    age: 52,
    email: 'evelyn71@burgerking.com',
    country: 'Kenya',
    jobTitle: 'Designer',
    department: 'Legal',
  },
  {
    name: 'Charlotte',
    gender: 'Female',
    company: 'Tesla',
    age: 34,
    email: 'charlotte72@tesla.com',
    country: 'USA',
    jobTitle: 'Analyst',
    department: 'HR',
  },
  {
    name: 'Molly',
    gender: 'Male',
    company: 'Swimlane',
    age: 52,
    email: 'molly73@swimlane.com',
    country: 'Kenya',
    jobTitle: 'Developer',
    department: 'Operations',
  },
  {
    name: 'Molly',
    gender: 'Male',
    company: 'Swimlane',
    age: 35,
    email: 'molly74@swimlane.com',
    country: 'France',
    jobTitle: 'Specialist',
    department: 'Finance',
  },
  {
    name: 'Harper',
    gender: 'Female',
    company: 'Amazon',
    age: 36,
    email: 'harper75@amazon.com',
    country: 'Japan',
    jobTitle: 'Consultant',
    department: 'Support',
  },
  {
    name: 'Mason',
    gender: 'Female',
    company: 'Tesla',
    age: 26,
    email: 'mason76@tesla.com',
    country: 'USA',
    jobTitle: 'Developer',
    department: 'Finance',
  },
  {
    name: 'Harper',
    gender: 'Female',
    company: 'Google',
    age: 30,
    email: 'harper77@google.com',
    country: 'Brazil',
    jobTitle: 'Architect',
    department: 'HR',
  },
  {
    name: 'Liam',
    gender: 'Male',
    company: 'Apple',
    age: 51,
    email: 'liam78@apple.com',
    country: 'Germany',
    jobTitle: 'Manager',
    department: 'Marketing',
  },
  {
    name: 'Emma',
    gender: 'Male',
    company: 'Burger King',
    age: 30,
    email: 'emma79@burgerking.com',
    country: 'Japan',
    jobTitle: 'Analyst',
    department: 'Finance',
  },
  {
    name: 'Isabella',
    gender: 'Female',
    company: 'Microsoft',
    age: 55,
    email: 'isabella80@microsoft.com',
    country: 'Canada',
    jobTitle: 'Consultant',
    department: 'Support',
  },
  {
    name: 'Liam',
    gender: 'Female',
    company: 'Swimlane',
    age: 31,
    email: 'liam81@swimlane.com',
    country: 'Canada',
    jobTitle: 'Consultant',
    department: 'Finance',
  },
  {
    name: 'Olivia',
    gender: 'Male',
    company: 'KFC',
    age: 38,
    email: 'olivia82@kfc.com',
    country: 'Germany',
    jobTitle: 'Designer',
    department: 'Legal',
  },
  {
    name: 'Liam',
    gender: 'Female',
    company: 'Netflix',
    age: 59,
    email: 'liam83@netflix.com',
    country: 'Australia',
    jobTitle: 'Analyst',
    department: 'IT',
  },
  {
    name: 'Mason',
    gender: 'Female',
    company: 'Tesla',
    age: 35,
    email: 'mason84@tesla.com',
    country: 'Brazil',
    jobTitle: 'Manager',
    department: 'Legal',
  },
  {
    name: 'Isabella',
    gender: 'Female',
    company: 'Amazon',
    age: 23,
    email: 'isabella85@amazon.com',
    country: 'France',
    jobTitle: 'Developer',
    department: 'Marketing',
  },
  {
    name: 'Sophia',
    gender: 'Female',
    company: 'Amazon',
    age: 45,
    email: 'sophia86@amazon.com',
    country: 'Kenya',
    jobTitle: 'Consultant',
    department: 'Marketing',
  },
  {
    name: 'Amelia',
    gender: 'Female',
    company: 'Burger King',
    age: 54,
    email: 'amelia87@burgerking.com',
    country: 'USA',
    jobTitle: 'Manager',
    department: 'Legal',
  },
  {
    name: 'Ethan',
    gender: 'Female',
    company: 'KFC',
    age: 47,
    email: 'ethan88@kfc.com',
    country: 'UK',
    jobTitle: 'Manager',
    department: 'Marketing',
  },
  {
    name: 'Dany',
    gender: 'Female',
    company: 'Apple',
    age: 30,
    email: 'dany89@apple.com',
    country: 'Kenya',
    jobTitle: 'Architect',
    department: 'Finance',
  },
  {
    name: 'Mason',
    gender: 'Male',
    company: 'KFC',
    age: 57,
    email: 'mason90@kfc.com',
    country: 'USA',
    jobTitle: 'Designer',
    department: 'Finance',
  },
  {
    name: 'Amelia',
    gender: 'Female',
    company: 'Tesla',
    age: 37,
    email: 'amelia91@tesla.com',
    country: 'France',
    jobTitle: 'Analyst',
    department: 'Legal',
  },
  {
    name: 'Noah',
    gender: 'Female',
    company: 'Swimlane',
    age: 35,
    email: 'noah92@swimlane.com',
    country: 'Kenya',
    jobTitle: 'Developer',
    department: 'Marketing',
  },
  {
    name: 'Noah',
    gender: 'Female',
    company: 'Google',
    age: 44,
    email: 'noah93@google.com',
    country: 'Kenya',
    jobTitle: 'Designer',
    department: 'Support',
  },
  {
    name: 'Ethan',
    gender: 'Male',
    company: 'Meta',
    age: 28,
    email: 'ethan94@meta.com',
    country: 'Brazil',
    jobTitle: 'Analyst',
    department: 'Legal',
  },
  {
    name: 'Austin',
    gender: 'Female',
    company: 'Meta',
    age: 60,
    email: 'austin95@meta.com',
    country: 'Australia',
    jobTitle: 'Analyst',
    department: 'Sales',
  },
  {
    name: 'Logan',
    gender: 'Male',
    company: 'Microsoft',
    age: 56,
    email: 'logan96@microsoft.com',
    country: 'Canada',
    jobTitle: 'Specialist',
    department: 'HR',
  },
  {
    name: 'James',
    gender: 'Male',
    company: 'Apple',
    age: 32,
    email: 'james97@apple.com',
    country: 'Australia',
    jobTitle: 'Engineer',
    department: 'IT',
  },
  {
    name: 'Mason',
    gender: 'Female',
    company: 'Burger King',
    age: 43,
    email: 'mason98@burgerking.com',
    country: 'Australia',
    jobTitle: 'Designer',
    department: 'IT',
  },
  {
    name: 'Lucas',
    gender: 'Female',
    company: 'Burger King',
    age: 26,
    email: 'lucas99@burgerking.com',
    country: 'Brazil',
    jobTitle: 'Analyst',
    department: 'Operations',
  },
];

export const columns = [
  { prop: 'name' },
  { name: 'Gender' },
  { name: 'Company' },
  { name: 'Age' },
  { name: 'Email', resizable: true },
  { name: 'Country' },
  { name: 'Job Title' },
  { name: 'Department' },
];
